#include "coredsl/LLVM23Emitter.h"

#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"

#include <functional>
#include <string>

namespace coredsl {

namespace {

const char *tableGenOperator(GenericOpcode Opcode) {
  switch (Opcode) {
  case GenericOpcode::Add:
    return "add";
  case GenericOpcode::Sub:
    return "sub";
  case GenericOpcode::Mul:
    return "mul";
  case GenericOpcode::And:
    return "and";
  case GenericOpcode::Or:
    return "or";
  case GenericOpcode::Xor:
    return "xor";
  case GenericOpcode::Shl:
    return "shl";
  case GenericOpcode::LShr:
    return "srl";
  case GenericOpcode::AShr:
    return "sra";
  }
  return "unknown";
}

void emitRegisterInfo(const TargetModel &Model, llvm::raw_ostream &OS) {
  const TargetConfigModel &Config = Model.Config;
  OS << "// Generated by coredsl-backend-gen. Do not edit.\n\n";
  OS << "let Namespace = \"" << Config.Namespace << "\" in {\n";
  for (unsigned I = 0; I != Config.RegisterCount; ++I)
    OS << "  def " << Config.RegisterPrefix << I << " : Register<\""
       << Config.RegisterPrefix << I << "\">;\n";
  OS << "}\n\ndef " << Config.RegisterClass << " : RegisterClass<\""
     << Config.Namespace << "\", [i" << Config.RegisterWidth << "], "
     << Config.RegisterWidth << ", (add ";
  for (unsigned I = 0; I != Config.RegisterCount; ++I) {
    if (I != 0)
      OS << ", ";
    OS << Config.RegisterPrefix << I;
  }
  OS << ")>;\n";
}

void emitRegisterBanks(const TargetModel &Model, llvm::raw_ostream &OS) {
  const TargetConfigModel &Config = Model.Config;
  OS << "// Generated by coredsl-backend-gen. Do not edit.\n";
  OS << "def " << Config.RegisterBank << " : RegisterBank<\""
     << Config.RegisterBank << "\", [" << Config.RegisterClass << "]>;\n";
}

bool isScalarRuleSupported(const TargetModel &Model,
                           const InstructionModel &Instruction) {
  if (!Instruction.SelectionRule)
    return false;
  const ValueTypeModel &Type =
      Instruction.Operands[Instruction.SelectionRule->OutputOperand].Type;
  return Type.K == ValueTypeModel::Kind::ScalarInteger &&
         Type.ScalarBits == Model.Config.RegisterWidth;
}

void emitInstructionInfo(const TargetModel &Model, llvm::raw_ostream &OS) {
  const TargetConfigModel &Config = Model.Config;
  OS << "// Generated by coredsl-backend-gen. Do not edit.\n\n";
  OS << "class " << Config.Namespace
     << "Inst<dag outs, dag ins, string asmstr> : Instruction {\n";
  OS << "  let Namespace = \"" << Config.Namespace << "\";\n";
  OS << "  let OutOperandList = outs;\n";
  OS << "  let InOperandList = ins;\n";
  OS << "  let AsmString = asmstr;\n";
  OS << "  let Pattern = [];\n";
  OS << "  let isPseudo = 1;\n";
  OS << "  let hasSideEffects = 0;\n";
  OS << "}\n\n";
  OS << "def COREDSL_RET : " << Config.Namespace
     << "Inst<(outs), (ins), \"RET\"> {\n";
  OS << "  let isReturn = 1;\n";
  OS << "  let isTerminator = 1;\n";
  OS << "  let isBarrier = 1;\n";
  OS << "}\n\n";
  for (const InstructionModel &Instruction : Model.Instructions) {
    if (!isScalarRuleSupported(Model, Instruction)) {
      OS << "// Not emitted: " << Instruction.Name
         << " has no supported scalar GlobalISel selection rule.\n";
      continue;
    }
    const SelectionRuleModel &Rule = *Instruction.SelectionRule;
    const OperandModel &Output = Instruction.Operands[Rule.OutputOperand];
    const OperandModel &LHS = Instruction.Operands[Rule.LHSOperand];
    const OperandModel &RHS = Instruction.Operands[Rule.RHSOperand];
    const std::string Type = Output.Type.tableGenType();
    OS << "def " << Instruction.Name << " : " << Config.Namespace << "Inst<"
       << "(outs " << Config.RegisterClass << ":$" << Output.Name << "), "
       << "(ins " << Config.RegisterClass << ":$" << LHS.Name << ", "
       << Config.RegisterClass << ":$" << RHS.Name << "), \""
       << Instruction.Name << " $" << Output.Name << ", $" << LHS.Name << ", $"
       << RHS.Name << "\">;\n\n";
    OS << "def : Pat<(" << Type << " (" << tableGenOperator(Rule.Opcode) << " ("
       << Type << " " << Config.RegisterClass << ":$" << LHS.Name << "), ("
       << Type << " " << Config.RegisterClass << ":$" << RHS.Name << "))), ("
       << Instruction.Name << " " << Config.RegisterClass << ":$" << LHS.Name
       << ", " << Config.RegisterClass << ":$" << RHS.Name << ")>;\n\n";
  }
}

using FileEmitter = std::function<void(llvm::raw_ostream &)>;

bool writeFile(llvm::StringRef Path, const FileEmitter &Emit,
               llvm::raw_ostream &Errors) {
  std::error_code EC;
  llvm::raw_fd_ostream OS(Path, EC, llvm::sys::fs::OF_Text);
  if (EC) {
    Errors << "error: cannot write '" << Path << "': " << EC.message() << '\n';
    return false;
  }
  Emit(OS);
  return true;
}

void emitCMakeLists(const TargetModel &Model, llvm::raw_ostream &OS) {
  const TargetConfigModel &Config = Model.Config;
  const std::string &NS = Config.Namespace;
  OS << "add_llvm_component_group(" << NS << ")\n\n";
  OS << "set(LLVM_TARGET_DEFINITIONS " << NS << ".td)\n\n";
  OS << "tablegen(LLVM " << NS << "GenGlobalISel.inc -gen-global-isel)\n";
  OS << "tablegen(LLVM " << NS << "GenInstrInfo.inc -gen-instr-info)\n";
  OS << "tablegen(LLVM " << NS << "GenRegisterBank.inc -gen-register-bank)\n";
  OS << "tablegen(LLVM " << NS << "GenRegisterInfo.inc -gen-register-info)\n";
  OS << "tablegen(LLVM " << NS << "GenSubtargetInfo.inc -gen-subtarget)\n\n";
  OS << "add_public_tablegen_target(" << NS << "CommonTableGen)\n\n";
  OS << "add_llvm_target(" << NS << "CodeGen\n";
  OS << "  " << NS << "Target.cpp\n\n";
  OS << "  LINK_COMPONENTS\n";
  OS << "  CodeGen\n";
  OS << "  Core\n";
  OS << "  GlobalISel\n";
  OS << "  MC\n";
  OS << "  " << NS << "Info\n";
  OS << "  Support\n";
  OS << "  Target\n";
  OS << "  TargetParser\n\n";
  OS << "  ADD_TO_COMPONENT\n";
  OS << "  " << NS << "\n";
  OS << "  )\n\n";
  OS << "add_subdirectory(TargetInfo)\n";
}

void emitTargetInfoHeader(const TargetModel &Model, llvm::raw_ostream &OS) {
  const std::string &NS = Model.Config.Namespace;
  OS << "#ifndef LLVM_LIB_TARGET_" << NS << "_TARGETINFO_" << NS
     << "TARGETINFO_H\n";
  OS << "#define LLVM_LIB_TARGET_" << NS << "_TARGETINFO_" << NS
     << "TARGETINFO_H\n\n";
  OS << "namespace llvm {\nclass Target;\nTarget &getThe" << NS
     << "Target();\n} // namespace llvm\n\n";
  OS << "#endif\n";
}

void emitTargetInfoSource(const TargetModel &Model, llvm::raw_ostream &OS) {
  const TargetConfigModel &Config = Model.Config;
  const std::string &NS = Config.Namespace;
  OS << "#include \"" << NS << "TargetInfo.h\"\n\n";
  OS << "#include \"llvm/MC/TargetRegistry.h\"\n";
  OS << "#include \"llvm/Support/Compiler.h\"\n\n";
  OS << "namespace llvm {\nTarget &getThe" << NS
     << "Target() {\n  static Target The" << NS << "Target;\n  return The" << NS
     << "Target;\n}\n} // namespace llvm\n\n";
  OS << "using namespace llvm;\n\n";
  OS << "extern \"C\" LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitialize"
     << NS << "TargetInfo() {\n";
  OS << "  TargetRegistry::RegisterTarget(getThe" << NS << "Target(), \""
     << Config.LLVMName << "\", \"Generated CoreDSL target\", \"" << NS
     << "\", [](Triple::ArchType) { return false; }, false);\n";
  OS << "}\n";
}

void emitTargetInfoCMake(const TargetModel &Model, llvm::raw_ostream &OS) {
  const std::string &NS = Model.Config.Namespace;
  OS << "add_llvm_component_library(LLVM" << NS << "Info\n";
  OS << "  " << NS << "TargetInfo.cpp\n\n";
  OS << "  LINK_COMPONENTS\n  MC\n  Support\n\n";
  OS << "  ADD_TO_COMPONENT\n  " << NS << "\n  )\n";
}

void emitTargetSource(const TargetModel &Model, llvm::raw_ostream &OS) {
  const TargetConfigModel &Config = Model.Config;
  const std::string &NS = Config.Namespace;
  OS << "#include \"TargetInfo/" << NS << "TargetInfo.h\"\n\n";
  OS << "#include \"llvm/ADT/BitVector.h\"\n";
  OS << "#include \"llvm/CodeGen/CodeGenTargetMachineImpl.h\"\n";
  OS << "#include \"llvm/CodeGen/GlobalISel/CallLowering.h\"\n";
  OS << "#include \"llvm/CodeGen/GlobalISel/IRTranslator.h\"\n";
  OS << "#include \"llvm/CodeGen/GlobalISel/InstructionSelect.h\"\n";
  OS << "#include \"llvm/CodeGen/GlobalISel/InstructionSelector.h\"\n";
  OS << "#include \"llvm/CodeGen/GlobalISel/Legalizer.h\"\n";
  OS << "#include \"llvm/CodeGen/GlobalISel/LegalizerInfo.h\"\n";
  OS << "#include \"llvm/CodeGen/GlobalISel/MachineIRBuilder.h\"\n";
  OS << "#include \"llvm/CodeGen/GlobalISel/RegBankSelect.h\"\n";
  OS << "#include \"llvm/CodeGen/RegisterBankInfo.h\"\n";
  OS << "#include \"llvm/CodeGen/TargetFrameLowering.h\"\n";
  OS << "#include \"llvm/CodeGen/TargetInstrInfo.h\"\n";
  OS << "#include \"llvm/CodeGen/TargetLowering.h\"\n";
  OS << "#include \"llvm/CodeGen/TargetLoweringObjectFileImpl.h\"\n";
  OS << "#include \"llvm/CodeGen/TargetOpcodes.h\"\n";
  OS << "#include \"llvm/CodeGen/TargetPassConfig.h\"\n";
  OS << "#include \"llvm/CodeGen/TargetRegisterInfo.h\"\n";
  OS << "#include \"llvm/CodeGen/TargetSubtargetInfo.h\"\n";
  OS << "#include \"llvm/InitializePasses.h\"\n";
  OS << "#include \"llvm/MC/MCAsmInfoELF.h\"\n";
  OS << "#include \"llvm/MC/MCInstrInfo.h\"\n";
  OS << "#include \"llvm/MC/MCRegisterInfo.h\"\n";
  OS << "#include \"llvm/MC/MCSubtargetInfo.h\"\n";
  OS << "#include \"llvm/MC/TargetRegistry.h\"\n";
  OS << "#include \"llvm/PassRegistry.h\"\n";
  OS << "#include \"llvm/Support/ErrorHandling.h\"\n\n";
  OS << "#include <memory>\n#include <optional>\n\n";
  OS << "#define GET_REGINFO_ENUM\n#include \"" << NS
     << "GenRegisterInfo.inc\"\n";
  OS << "#define GET_INSTRINFO_ENUM\n#include \"" << NS
     << "GenInstrInfo.inc\"\n";
  OS << "#define GET_REGINFO_HEADER\n#include \"" << NS
     << "GenRegisterInfo.inc\"\n";
  OS << "#define GET_INSTRINFO_HEADER\n#include \"" << NS
     << "GenInstrInfo.inc\"\n";
  OS << "#define GET_SUBTARGETINFO_HEADER\n#include \"" << NS
     << "GenSubtargetInfo.inc\"\n";
  OS << "#define GET_REGBANK_DECLARATIONS\n#include \"" << NS
     << "GenRegisterBank.inc\"\n\n";
  OS << "namespace llvm {\n\n";
  OS << "class " << NS << "Subtarget;\n\n";
  OS << "class " << NS
     << "GenRegisterBankInfo : public RegisterBankInfo {\n"
        "protected:\n"
        "#define GET_TARGET_REGBANK_CLASS\n"
        "#include \""
     << NS << "GenRegisterBank.inc\"\n};\n\n";
  OS << "class " << NS << "RegisterBankInfo final : public " << NS
     << "GenRegisterBankInfo {\n"
        "public:\n  "
     << NS
     << "RegisterBankInfo();\n"
        "  const InstructionMapping &\n"
        "  getInstrMapping(const MachineInstr &MI) const override;\n"
        "};\n\n";
  OS << "class " << NS << "LegalizerInfo final : public LegalizerInfo {\n"
     << "public:\n  " << NS
     << "LegalizerInfo() {\n"
        "    using namespace TargetOpcode;\n"
        "    getActionDefinitionsBuilder({";
  bool FirstOpcode = true;
  for (const InstructionModel &Instruction : Model.Instructions) {
    if (!isScalarRuleSupported(Model, Instruction))
      continue;
    if (!FirstOpcode)
      OS << ", ";
    FirstOpcode = false;
    OS << genericOpcodeName(Instruction.SelectionRule->Opcode);
  }
  OS << "}).legalFor({LLT::scalar(" << Config.RegisterWidth << ")});\n"
     << "  }\n};\n\n";
  OS << "class " << NS << "CallLowering final : public CallLowering {\n"
     << "public:\n  explicit " << NS
     << "CallLowering(const TargetLowering *TLI) : CallLowering(TLI) {}\n\n"
        "  bool lowerReturn(MachineIRBuilder &MIRBuilder, const Value *Val,\n"
        "                   ArrayRef<Register> VRegs,\n"
        "                   FunctionLoweringInfo &) const override {\n"
        "    if (!Val && !VRegs.empty())\n"
        "      return false;\n"
        "    if (Val) {\n"
        "      if (VRegs.size() != 1 ||\n"
        "          MIRBuilder.getMRI()->getType(VRegs[0]) != LLT::scalar("
     << Config.RegisterWidth
     << "))\n"
        "        return false;\n"
        "      MIRBuilder.buildCopy(Register("
     << NS << "::" << Config.RegisterPrefix
     << "0), VRegs[0]);\n"
        "    }\n"
        "    MachineInstrBuilder Return = MIRBuilder.buildInstr("
     << NS
     << "::COREDSL_RET);\n"
        "    if (Val)\n"
        "      Return.addUse(Register("
     << NS << "::" << Config.RegisterPrefix
     << "0), RegState::Implicit);\n"
        "    return true;\n"
        "  }\n\n"
        "  bool lowerFormalArguments(MachineIRBuilder &MIRBuilder, const "
        "Function &F,\n"
        "                            ArrayRef<ArrayRef<Register>> VRegs,\n"
        "                            FunctionLoweringInfo &) const override {\n"
        "    static constexpr MCPhysReg ArgRegs[] = {";
  for (unsigned I = 0; I != Config.RegisterCount; ++I) {
    if (I != 0)
      OS << ", ";
    OS << NS << "::" << Config.RegisterPrefix << I;
  }
  OS << "};\n"
        "    if (F.isVarArg() || VRegs.size() > "
     << Config.RegisterCount
     << ")\n"
        "      return false;\n"
        "    MachineRegisterInfo &MRI = *MIRBuilder.getMRI();\n"
        "    for (unsigned I = 0; I != VRegs.size(); ++I) {\n"
        "      if (VRegs[I].size() != 1 ||\n"
        "          MRI.getType(VRegs[I][0]) != LLT::scalar("
     << Config.RegisterWidth
     << "))\n"
        "        return false;\n"
        "      MRI.addLiveIn(ArgRegs[I]);\n"
        "      MIRBuilder.getMBB().addLiveIn(ArgRegs[I]);\n"
        "      MIRBuilder.buildCopy(VRegs[I][0], Register(ArgRegs[I]));\n"
        "    }\n"
        "    return true;\n"
        "  }\n"
        "};\n\n";
  OS << "class " << NS << "FrameLowering final : public TargetFrameLowering {\n"
     << "public:\n  " << NS << "FrameLowering()\n"
     << "      : TargetFrameLowering(StackGrowsDown, Align(1), 0, Align(1)) "
        "{}\n"
     << "  void emitPrologue(MachineFunction &, MachineBasicBlock &) const "
        "override {}\n"
     << "  void emitEpilogue(MachineFunction &, MachineBasicBlock &) const "
        "override {}\n"
     << "protected:\n  bool hasFPImpl(const MachineFunction &) const override "
        "{ return false; }\n"
     << "};\n\n";
  OS << "class " << NS << "RegisterInfo final : public " << NS
     << "GenRegisterInfo {\npublic:\n  " << NS << "RegisterInfo() : " << NS
     << "GenRegisterInfo(" << NS << "::" << Config.RegisterPrefix << "0) {}\n";
  OS << "  const MCPhysReg *getCalleeSavedRegs(const MachineFunction *) const "
        "override { return nullptr; }\n";
  OS << "  const uint32_t *getCallPreservedMask(const MachineFunction &, "
        "CallingConv::ID) const override { return nullptr; }\n";
  OS << "  BitVector getReservedRegs(const MachineFunction &) const override { "
        "return BitVector(getNumRegs()); }\n";
  OS << "  bool eliminateFrameIndex(MachineBasicBlock::iterator, int, "
        "unsigned, RegScavenger *) const override { report_fatal_error(\"frame "
        "indices are outside the GlobalISel-only CoreDSL target\"); }\n";
  OS << "  Register getFrameRegister(const MachineFunction &) const override { "
        "return "
     << NS << "::" << Config.RegisterPrefix << "0; }\n};\n\n";
  OS << "class " << NS << "InstrInfo final : public " << NS
     << "GenInstrInfo {\n  " << NS << "RegisterInfo RI;\npublic:\n  explicit "
     << NS << "InstrInfo(const TargetSubtargetInfo &STI) : " << NS
     << "GenInstrInfo(STI, RI) {}\n  const " << NS
     << "RegisterInfo &getRegisterInfo() const { return RI; }\n};\n\n";
  OS << "class " << NS
     << "InstructionSelector final : public InstructionSelector {\n  const "
     << NS << "InstrInfo &TII;\n  const " << NS
     << "RegisterInfo &TRI;\n  const " << NS
     << "RegisterBankInfo &RBI;\npublic:\n  " << NS
     << "InstructionSelector(const " << NS << "InstrInfo &TII, const " << NS
     << "RegisterBankInfo &RBI)\n"
        "      : TII(TII), TRI(TII.getRegisterInfo()), RBI(RBI) {}\n";
  OS << "  bool select(MachineInstr &MI) override {\n";
  OS << "    if (!isPreISelGenericOpcode(MI.getOpcode())) return true;\n";
  OS << "    switch (MI.getOpcode()) {\n";
  for (const InstructionModel &Instruction : Model.Instructions) {
    if (!isScalarRuleSupported(Model, Instruction))
      continue;
    OS << "    case TargetOpcode::"
       << genericOpcodeName(Instruction.SelectionRule->Opcode)
       << ": MI.setDesc(TII.get(" << NS << "::" << Instruction.Name
       << ")); break;\n";
  }
  OS << "    default: return false;\n"
        "    }\n"
        "    constrainSelectedInstRegOperands(MI, TII, TRI, RBI);\n"
        "    return true;\n"
        "  }\n";
  OS << "  void setupGeneratedPerFunctionState(MachineFunction &) override "
        "{}\n};\n\n";
  OS << "class " << NS << "Subtarget final : public " << NS
     << "GenSubtargetInfo {\n  " << NS << "InstrInfo InstrInfo;\n  " << NS
     << "FrameLowering FrameLowering;\n  std::unique_ptr<TargetLowering> "
        "Lowering;\n  std::unique_ptr<"
     << NS << "LegalizerInfo> Legalizer;\n  std::unique_ptr<" << NS
     << "RegisterBankInfo> RegBankInfo;\n  std::unique_ptr<" << NS
     << "CallLowering> CallLoweringInfo;\n  "
        "std::unique_ptr<InstructionSelector> "
        "Selector;\npublic:\n  "
     << NS
     << "Subtarget(const Triple &TT, StringRef CPU, StringRef FS, const "
        "TargetMachine &TM)\n"
     << "      : " << NS
     << "GenSubtargetInfo(TT, CPU, CPU, FS), InstrInfo(*this) {\n"
     << "    Lowering = std::make_unique<TargetLowering>(TM, *this);\n"
     << "    Legalizer = std::make_unique<" << NS << "LegalizerInfo>();\n"
     << "    RegBankInfo = std::make_unique<" << NS << "RegisterBankInfo>();\n"
     << "    CallLoweringInfo = std::make_unique<" << NS
     << "CallLowering>(Lowering.get());\n"
     << "    Selector = std::make_unique<" << NS
     << "InstructionSelector>(InstrInfo, *RegBankInfo);\n  }\n"
     << "  const " << NS
     << "InstrInfo *getInstrInfo() const override { return &InstrInfo; }\n"
     << "  const " << NS
     << "RegisterInfo *getRegisterInfo() const override { return "
        "&InstrInfo.getRegisterInfo(); }\n"
     << "  const " << NS
     << "FrameLowering *getFrameLowering() const override { return "
        "&FrameLowering; }\n"
     << "  const TargetLowering *getTargetLowering() const override { return "
        "Lowering.get(); }\n"
     << "  const LegalizerInfo *getLegalizerInfo() const override { return "
        "Legalizer.get(); }\n"
     << "  const RegisterBankInfo *getRegBankInfo() const override { return "
        "RegBankInfo.get(); }\n"
     << "  const CallLowering *getCallLowering() const override { return "
        "CallLoweringInfo.get(); }\n"
     << "  InstructionSelector *getInstructionSelector() const override { "
        "return Selector.get(); }\n"
     << "  void ParseSubtargetFeatures(StringRef CPU, StringRef TuneCPU, "
        "StringRef FS);\n"
     << "};\n\n";
  OS << "} // namespace llvm\n\n";
  OS << "#define DEBUG_TYPE \"" << Config.LLVMName << "-subtarget\"\n";
  OS << "#define GET_SUBTARGETINFO_TARGET_DESC\n#define "
        "GET_SUBTARGETINFO_CTOR\n#include \""
     << NS << "GenSubtargetInfo.inc\"\n";
  OS << "#undef DEBUG_TYPE\n\n";
  OS << "#define GET_TARGET_REGBANK_IMPL\n#include \"" << NS
     << "GenRegisterBank.inc\"\n\n";
  OS << "namespace llvm {\n\n";
  OS << NS << "RegisterBankInfo::" << NS << "RegisterBankInfo()\n"
     << "    : " << NS << "GenRegisterBankInfo() {}\n\n";
  OS << "const RegisterBankInfo::InstructionMapping &\n"
     << NS
     << "RegisterBankInfo::getInstrMapping(const MachineInstr &MI) const {\n"
        "  if (!isPreISelGenericOpcode(MI.getOpcode())) {\n"
        "    const InstructionMapping &Mapping = getInstrMappingImpl(MI);\n"
        "    if (Mapping.isValid())\n"
        "      return Mapping;\n"
        "  }\n\n"
        "  switch (MI.getOpcode()) {\n";
  for (const InstructionModel &Instruction : Model.Instructions) {
    if (!isScalarRuleSupported(Model, Instruction))
      continue;
    OS << "  case TargetOpcode::"
       << genericOpcodeName(Instruction.SelectionRule->Opcode) << ":\n";
  }
  OS << "    break;\n"
        "  default:\n"
        "    return getInvalidInstructionMapping();\n"
        "  }\n\n"
        "  const ValueMapping &GPRMapping =\n"
        "      getValueMapping(0, "
     << Config.RegisterWidth << ", getRegBank(" << NS
     << "::" << Config.RegisterBank
     << "ID));\n"
        "  const ValueMapping *Operands =\n"
        "      getOperandsMapping({&GPRMapping, &GPRMapping, &GPRMapping});\n"
        "  return getInstructionMapping(DefaultMappingID, 1, Operands,\n"
        "                               MI.getNumOperands());\n"
        "}\n\n";
  OS << "class " << NS
     << "TargetMachine final : public CodeGenTargetMachineImpl {\n"
     << "  std::unique_ptr<TargetLoweringObjectFile> ObjectFile;\n  " << NS
     << "Subtarget Subtarget;\npublic:\n  " << NS
     << "TargetMachine(const Target &T, const Triple &TT, StringRef CPU, "
        "StringRef FS, const TargetOptions &Options, "
        "std::optional<Reloc::Model> RM, std::optional<CodeModel::Model> CM, "
        "CodeGenOptLevel OL, bool)\n"
     << "      : CodeGenTargetMachineImpl(T, TT.computeDataLayout(), TT, CPU, "
        "FS, Options, RM.value_or(Reloc::Static), "
        "CM.value_or(CodeModel::Small), OL), "
        "ObjectFile(std::make_unique<TargetLoweringObjectFileELF>()), "
        "Subtarget(TT, CPU, FS, *this) {\n"
        "    initAsmInfo();\n"
        "    setGlobalISel(true);\n"
        "    setFastISel(false);\n"
        "    setO0WantsFastISel(false);\n"
        "  }\n"
     << "  const " << NS
     << "Subtarget *getSubtargetImpl(const Function &) const override { return "
        "&Subtarget; }\n"
     << "  TargetLoweringObjectFile *getObjFileLowering() const override { "
        "return ObjectFile.get(); }\n"
        "  TargetPassConfig *createPassConfig(PassManagerBase &PM) override;\n"
        "};\n\n";
  OS << "class " << NS
     << "PassConfig final : public TargetPassConfig {\n"
        "public:\n  "
     << NS << "PassConfig(" << NS
     << "TargetMachine &TM, PassManagerBase &PM)\n"
        "      : TargetPassConfig(TM, PM) {}\n\n"
        "  bool addIRTranslator() override {\n"
        "    addPass(new IRTranslator());\n"
        "    return false;\n"
        "  }\n"
        "  bool addLegalizeMachineIR() override {\n"
        "    addPass(new Legalizer());\n"
        "    return false;\n"
        "  }\n"
        "  bool addRegBankSelect() override {\n"
        "    addPass(new RegBankSelect());\n"
        "    return false;\n"
        "  }\n"
        "  bool addGlobalInstructionSelect() override {\n"
        "    addPass(new InstructionSelect());\n"
        "    return false;\n"
        "  }\n"
        "};\n\n";
  OS << "TargetPassConfig *" << NS
     << "TargetMachine::createPassConfig(PassManagerBase &PM) {\n"
        "  return new "
     << NS << "PassConfig(*this, PM);\n}\n\n";
  OS << "} // namespace llvm\n\n";
  // The TableGen descriptions provide declarations through the *_HEADER
  // sections above.  A deliberately compact generated backend keeps the
  // corresponding definitions in this one translation unit.
  OS << "#define GET_REGINFO_MC_DESC\n#include \"" << NS
     << "GenRegisterInfo.inc\"\n";
  OS << "#define GET_INSTRINFO_MC_DESC\n#define GET_INSTRINFO_CTOR_DTOR\n"
     << "#include \"" << NS << "GenInstrInfo.inc\"\n";
  OS << "#define GET_SUBTARGETINFO_MC_DESC\n#include \"" << NS
     << "GenSubtargetInfo.inc\"\n";
  OS << "#define GET_REGINFO_TARGET_DESC\n#include \"" << NS
     << "GenRegisterInfo.inc\"\n";
  OS << "\n";
  OS << "using namespace llvm;\n\n";
  OS << "namespace {\n\n";
  OS << "class " << NS << "MCAsmInfo final : public MCAsmInfoELF {\npublic:\n"
     << "  " << NS
     << "MCAsmInfo(const Triple &, const MCTargetOptions &Options)\n"
     << "      : MCAsmInfoELF(Options) { CodePointerSize = "
     << Config.RegisterWidth / 8 << "; }\n};\n\n";
  OS << "MCInstrInfo *create" << NS << "MCInstrInfo() {\n"
     << "  auto *Info = new MCInstrInfo();\n  Init" << NS
     << "MCInstrInfo(Info);\n  return Info;\n}\n\n";
  OS << "MCRegisterInfo *create" << NS << "MCRegisterInfo(const Triple &) {\n"
     << "  auto *Info = new MCRegisterInfo();\n  Init" << NS
     << "MCRegisterInfo(Info, " << NS << "::" << Config.RegisterPrefix
     << "0);\n  return Info;\n}\n\n";
  OS << "MCSubtargetInfo *create" << NS
     << "MCSubtargetInfo(const Triple &TT, StringRef CPU, StringRef FS) {\n"
     << "  return create" << NS
     << "MCSubtargetInfoImpl(TT, CPU, CPU, FS);\n}\n\n";
  OS << "} // namespace\n\n";
  OS << "extern \"C\" LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitialize"
     << NS << "Target() {\n  RegisterTargetMachine<" << NS
     << "TargetMachine> X(getThe" << NS << "Target());\n"
     << "  initializeGlobalISel(*PassRegistry::getPassRegistry());\n}\n";
  // GlobalISel's pass runner constructs a MachineModuleInfo and therefore
  // requires MC context objects.  These registrations deliberately omit an
  // assembler, code emitter and object writer.
  OS << "extern \"C\" LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitialize"
     << NS << "TargetMC() {\n  RegisterMCAsmInfo<" << NS
     << "MCAsmInfo> A(getThe" << NS << "Target());\n"
     << "  TargetRegistry::RegisterMCInstrInfo(getThe" << NS
     << "Target(), create" << NS << "MCInstrInfo);\n"
     << "  TargetRegistry::RegisterMCRegInfo(getThe" << NS << "Target(), create"
     << NS << "MCRegisterInfo);\n"
     << "  TargetRegistry::RegisterMCSubtargetInfo(getThe" << NS
     << "Target(), create" << NS << "MCSubtargetInfo);\n}\n";
}

} // namespace

void emitLLVM23TableGen(const TargetModel &Model, llvm::raw_ostream &OS) {
  const TargetConfigModel &Config = Model.Config;
  OS << "//===-- " << Config.Namespace
     << ".td - Generated CoreDSL target -------*- tablegen -*-===//\n\n";
  OS << "include \"llvm/Target/Target.td\"\n";
  OS << "\n";
  emitRegisterInfo(Model, OS);
  OS << "\n";
  emitRegisterBanks(Model, OS);
  OS << "\n";
  emitInstructionInfo(Model, OS);
  OS << "defm : RemapAllTargetPseudoPointerOperands<" << Config.RegisterClass
     << ">;\n\n";
  OS << "def " << Config.Namespace << "InstrInfo : InstrInfo;\n";
  OS << "def " << Config.Namespace << " : Target {\n";
  OS << "  let InstructionSet = " << Config.Namespace << "InstrInfo;\n";
  OS << "}\n";
}

bool emitLLVM23Backend(const TargetModel &Model,
                       llvm::StringRef OutputDirectory,
                       llvm::raw_ostream &Errors) {
  if (llvm::sys::fs::exists(OutputDirectory)) {
    Errors << "error: output directory already exists: '" << OutputDirectory
           << "'\n";
    return false;
  }

  std::error_code EC = llvm::sys::fs::create_directories(OutputDirectory);
  if (EC) {
    Errors << "error: cannot create output directory '" << OutputDirectory
           << "': " << EC.message() << '\n';
    return false;
  }
  auto appendPath = [](llvm::StringRef Directory, llvm::StringRef Name) {
    llvm::SmallString<256> Result(Directory);
    llvm::sys::path::append(Result, Name);
    return Result.str().str();
  };
  const std::string TargetInfoDirectory =
      appendPath(OutputDirectory, "TargetInfo");
  if ((EC = llvm::sys::fs::create_directories(TargetInfoDirectory))) {
    Errors << "error: cannot create TargetInfo directory: " << EC.message()
           << '\n';
    return false;
  }

  const std::string &NS = Model.Config.Namespace;
  auto path = [&](llvm::StringRef Name) {
    return appendPath(OutputDirectory, Name);
  };
  auto targetInfoPath = [&](llvm::StringRef Name) {
    return appendPath(TargetInfoDirectory, Name);
  };
  return writeFile(
             path("CMakeLists.txt"),
             [&](llvm::raw_ostream &OS) { emitCMakeLists(Model, OS); },
             Errors) &&
         writeFile(
             path(NS + ".td"),
             [&](llvm::raw_ostream &OS) { emitLLVM23TableGen(Model, OS); },
             Errors) &&
         writeFile(
             path(NS + "Target.cpp"),
             [&](llvm::raw_ostream &OS) { emitTargetSource(Model, OS); },
             Errors) &&
         writeFile(
             targetInfoPath("CMakeLists.txt"),
             [&](llvm::raw_ostream &OS) { emitTargetInfoCMake(Model, OS); },
             Errors) &&
         writeFile(
             targetInfoPath(NS + "TargetInfo.h"),
             [&](llvm::raw_ostream &OS) { emitTargetInfoHeader(Model, OS); },
             Errors) &&
         writeFile(
             targetInfoPath(NS + "TargetInfo.cpp"),
             [&](llvm::raw_ostream &OS) { emitTargetInfoSource(Model, OS); },
             Errors);
}

} // namespace coredsl
