// Example only: construct legalizer template data and render it with LLVM APIs.

#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Mustache.h"
#include "llvm/Support/StringSaver.h"
#include "llvm/Support/raw_ostream.h"

#include <utility>

using namespace llvm;

static json::Value makeLegalizerInput() {
  json::Object Root;
  Root["generated_notice"] =
      "// Generated by the target description compiler. Do not edit.";
  Root["header_guard"] = "LLVM_LIB_TARGET_EXAMPLE_EXAMPLELEGALIZERINFO_H";
  Root["header_include"] = "ExampleLegalizerInfo.h";
  Root["cpp_namespace"] = "llvm";
  Root["class_name"] = "ExampleLegalizerInfo";

  Root["header_includes"] = json::Array{};

  json::Object IntrinsicsHeader;
  IntrinsicsHeader["path"] = "llvm/IR/IntrinsicsExample.h";
  json::Array SourceIncludes;
  SourceIncludes.emplace_back(std::move(IntrinsicsHeader));
  Root["source_includes"] = std::move(SourceIncludes);

  json::Array IntegerWidths;
  IntegerWidths.emplace_back(16);
  IntegerWidths.emplace_back(32);

  json::Object NativeTypes;
  NativeTypes["integer_widths"] = std::move(IntegerWidths);
  NativeTypes["floating_point_types"] = json::Array{};
  Root["native_types"] = std::move(NativeTypes);

  json::Array ScalarArgumentIndices;
  ScalarArgumentIndices.emplace_back(0);

  json::Object Intrinsic;
  Intrinsic["id_cpp"] = "Intrinsic::example_f16_op";
  Intrinsic["scalar_argument_indices"] = std::move(ScalarArgumentIndices);

  json::Array Intrinsics;
  Intrinsics.emplace_back(std::move(Intrinsic));
  Root["intrinsics"] = std::move(Intrinsics);

  return json::Value(std::move(Root));
}

static Error renderTemplate(StringRef TemplatePath, const json::Value &Data,
                            raw_ostream &OS) {
  auto TemplateOrError = MemoryBuffer::getFile(TemplatePath);
  if (!TemplateOrError)
    return errorCodeToError(TemplateOrError.getError());

  BumpPtrAllocator Allocator;
  StringSaver Saver(Allocator);
  mustache::MustacheContext Context(Allocator, Saver);
  mustache::Template Template((*TemplateOrError)->getBuffer(), Context);

  // LLVM Mustache defaults to HTML escaping. Generated C++ must be emitted
  // verbatim, including possible '<', '>', '&', quote, and apostrophe tokens.
  Template.overrideEscapeCharacters(mustache::EscapeMap{});
  Template.render(Data, OS);
  return Error::success();
}

int main(int Argc, char **Argv) {
  if (Argc != 2) {
    errs() << "usage: llvm-api-render-example <template.mustache>\n";
    return 1;
  }

  ExitOnError ExitOnErr("llvm-api-render-example: ");
  json::Value Data = makeLegalizerInput();
  ExitOnErr(renderTemplate(Argv[1], Data, outs()));
  return 0;
}
